name: amategeko
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+26 # version 26

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  splash_screen_view: any
  flutter_svg: ^1.0.0
  #  device_info: ^2.0.0
  flutter_linkify: ^6.0.0
  uni_links: ^0.5.1
  flutter_local_notifications: ^12.0.4
  curved_navigation_bar: ^1.0.3
  fluttertoast: ^8.1.2
  http: ^0.13.0
  firebase_messaging: ^14.2.1
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.4.4
  url_launcher: ^6.1.9
  share_plus: any
  connectivity_plus: ^4.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.0.2
  file_picker: ^5.0.0
  shared_preferences: ^2.0.15
  image_network: ^2.5.2
  random_string: ^2.0.1
  image_picker: ^0.8.6
  collection: ^1.15.0
  firebase_storage: ^11.0.6
  syncfusion_flutter_pdfviewer: ^20.4.51
  device_info_plus: ^9.0.1
  dbus: ^0.7.8
  upgrader: ^8.0.0
  uuid: ^3.0.7
  flutter_phone_direct_caller: ^2.1.1
  just_audio: ^0.9.11
  visibility_detector: ^0.4.0+2
  screenshot_callback: ^3.0.1
  flutter_windowmanager: ^0.2.0
  crypto: ^3.0.3
  google_mobile_ads:
  flutterwave_standard: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  dart_code_metrics: ^5.5.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/files/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
