// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKBBoj4exwSJObrKViL13LhEnPTI3yzek',
    appId: '1:922737655486:web:a6295a479fb1e53900e8ef',
    messagingSenderId: '922737655486',
    projectId: 'amategeko-75e59',
    authDomain: 'amategeko-75e59.firebaseapp.com',
    storageBucket: 'amategeko-75e59.appspot.com',
    measurementId: 'G-DL7QT8DWN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHUOH3OXVNc8VCZ3uWZEIulXktgeKMDEM',
    appId: '1:922737655486:android:e8f04075bcd317d200e8ef',
    messagingSenderId: '922737655486',
    projectId: 'amategeko-75e59',
    storageBucket: 'amategeko-75e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKx37RNCHNJYTb0tic-Zv5OVWsESPaFbI',
    appId: '1:922737655486:ios:6b68109df5d7d0ee00e8ef',
    messagingSenderId: '922737655486',
    projectId: 'amategeko-75e59',
    storageBucket: 'amategeko-75e59.appspot.com',
    iosClientId: '922737655486-mo3ohnn7fjguttntm15bt3ll5034p505.apps.googleusercontent.com',
    iosBundleId: 'com.amategeko.amategeko',
  );
}
