// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9FMzVbK2sSLDjCGR13aHMmeyUddJQi3Q',
    appId: '1:760178305900:web:cac0e55cd8d124e8ca2149',
    messagingSenderId: '760178305900',
    projectId: 'rwanda-traffic-rules-c7e18',
    authDomain: 'rwanda-traffic-rules-c7e18.firebaseapp.com',
    storageBucket: 'rwanda-traffic-rules-c7e18.firebasestorage.app',
    measurementId: 'G-8R9FKMNH16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuacBFYALZ0Ho2r2Vo7U8VqPty9scOzYw',
    appId: '1:760178305900:android:c31cb0fa5b71b0deca2149',
    messagingSenderId: '760178305900',
    projectId: 'rwanda-traffic-rules-c7e18',
    storageBucket: 'rwanda-traffic-rules-c7e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKRtR_xmoPsqXDvC1-xGxANC69nFBXB8I',
    appId: '1:760178305900:ios:eeb6306da3966bf1ca2149',
    messagingSenderId: '760178305900',
    projectId: 'rwanda-traffic-rules-c7e18',
    storageBucket: 'rwanda-traffic-rules-c7e18.firebasestorage.app',
    iosBundleId: 'com.rwanda.trafficrules',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeovxbXwUv5tLVyX3kANZRomx20wgtIRU',
    appId: '1:788538011169:ios:5bbf9c072fd9143258bd60',
    messagingSenderId: '788538011169',
    projectId: 'rwanda-traffic-rules',
    storageBucket: 'rwanda-traffic-rules.appspot.com',
    iosBundleId: 'com.rwanda.trafficrules',
  );
}