// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqH8FYOCP-lWAJV7cDtIPG0Q6aIOTmNEA',
    appId: '1:788538011169:web:db9714958a28426e58bd60',
    messagingSenderId: '788538011169',
    projectId: 'rwanda-traffic-rules',
    authDomain: 'rwanda-traffic-rules.firebaseapp.com',
    storageBucket: 'rwanda-traffic-rules.appspot.com',
    measurementId: 'G-1E52QCDC3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdG442FjC40vr6P4eLa_-8Bj3_cDcFXA',
    appId: '1:788538011169:android:71644dca4687eb7d58bd60',
    messagingSenderId: '788538011169',
    projectId: 'rwanda-traffic-rules',
    storageBucket: 'rwanda-traffic-rules.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeovxbXwUv5tLVyX3kANZRomx20wgtIRU',
    appId: '1:788538011169:ios:5bbf9c072fd9143258bd60',
    messagingSenderId: '788538011169',
    projectId: 'rwanda-traffic-rules',
    storageBucket: 'rwanda-traffic-rules.appspot.com',
    iosBundleId: 'com.amategeko.amategeko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeovxbXwUv5tLVyX3kANZRomx20wgtIRU',
    appId: '1:788538011169:ios:5bbf9c072fd9143258bd60',
    messagingSenderId: '788538011169',
    projectId: 'rwanda-traffic-rules',
    storageBucket: 'rwanda-traffic-rules.appspot.com',
    iosBundleId: 'com.amategeko.amategeko',
  );
}
